### ISSUE TITLE
How to replace ipsum lorum text

### ISSUE THREAD

**Issue by mikkelking** [DeviaVir/ghost-interphase-theme#4]
I applied the theme to my blog, but there is boiler plate which I can't see how to edit - what am I missing?

**Comment by DeviaVir** [comment]
@mikkelking this boilerplate can only be edited in the theme itself, since Ghost does not support editing themes or static modules directly (yet).

You can edit it here: https://github.com/DeviaVir/ghost-interphase-theme/blob/master/index.hbs#L16 and your footer can be updated here: https://github.com/DeviaVir/ghost-interphase-theme/blob/master/default.hbs#L40
